language: python
python: 3.6
branches:
  only:
    - "master"
before_install: |
  sudo apt-get -qq update
  sudo apt-get -y install vim
install:
  pip install vim-vint==0.3.21
cache: pip
script:
  - make lint
  - make test
